### ISSUE TITLE
Color value conversion RGB to HSL

### ISSUE THREAD

**Issue by kirubasankars** [ColorCop/ColorCop#11]
Hi there, 

This is not a bug.

I am using this tool for almost last 7 years. big thanks for your contribution. 

How are you converting rbg to hsl or other way?
![color](https://cloud.githubusercontent.com/assets/2040058/16698578/f7cfe4b4-451c-11e6-870f-10948f250e67.PNG)

Yours does not match with following calculator
[RGB2HSL](http://www.rapidtables.com/convert/color/rgb-to-hsl.htm)

Sorry. Its very hard for me to following this on the code.

**Comment by jerone** [comment]
Even http://colorizer.org shows an different result `hsl(4.8, 69.5%, 53.7%)`.
