### ISSUE TITLE
Color Cop Help file

### ISSUE THREAD

**Issue by flutternoob** [ColorCop/ColorCop#21]
@j4y 

The Color Cop help file is in the outdated *.hlp format. I converted the help file using an online converter to the *.html format. However, that messed up the formatting. So, I took the liberty of re-creating the help file (using the converted file) as best as I could in the *.docx and subsequent *.pdf formats.

Thank you for a great application. 

[ColorCop Help File-final.pdf](https://github.com/ColorCop/ColorCop/files/5898358/ColorCop.Help.File-final.pdf)
[ColorCop Help File-final.docx](https://github.com/ColorCop/ColorCop/files/5898359/ColorCop.Help.File-final.docx)

**Comment by dodedodo** [comment]
That's very nice of you @flutternoob. Unfortunately, this project is neither open-source nor maintained, so I don't expect your contribution to be incorporated into ColorCop :(

**Comment by flutternoob** [comment]
That's ok.

**Comment by flutternoob** [comment]
Thats ok. What would you suggest i do to make this help file available to
users of Color Cop?
