### ISSUE TITLE
Unmerged and different license file compared to website

### ISSUE THREAD

**Issue by Shoozza** [ColorCop/ColorCop#23]
Hello,

I noticed that the repo license file for the installer has unmerged changes:
https://github.com/ColorCop/ColorCop/blob/master/packaging/license.txt

Also the license on the website and the repo differ :
http://colorcop.net/license/

Btw I noticed that there are some custom changes in the license on the website (based on the MIT License).
Would it be possible to move to a default opensource license instead of a restricted custom one?
https://opensource.org/licenses

Thanks :)

**Comment by dodedodo** [comment]
Hey @Shoozza. This repository has not been maintained since 2015. Colorcop is unfortunately copyrighted, and I don't expect the owner to respond to your request.

**Comment by j4y** [comment]
Someone must have helped me put that together, but I don’t remember.

I am open to changing it, but would like to understand why you want that.

@Shoozza @dodedodo what do you think?

**Comment by Shoozza** [comment]
Hello thanks for the reply!

There are a few reasons I think licensing it under an open source license might be helpful:

1. **More likely to be promoted** as people are happy to share open source software
1. **Easier to contribute** as open source licenses like the [MIT License](https://choosealicense.com/licenses/mit/) are well understood among developers and allow for contribution
1. **Chance to be ported to other systems** such as Linux

Not sure if all of these apply to ColorCop as it's stable but it would be nice if several decades from now someone could still make sure it works with the latest windows version.
